const summerWoman = [
  // https://www.asos.com/api/product/search/v2/categories/50599?offset=0&sort=pricedesc&store=FR&lang=fr-FR&currency=EUR&rowlength=4&channel=desktop-web&country=FR&keyStoreDataversion=ornjx7v-36&advertisementsPartnerId=100714&advertisementsVisitorId=e2af8cf6-d6ee-4270-9958-57886c9c4b2c&advertisementsOptInConsent=true&limit=30&attribute_10992=61379
  {
    id: 204878684,
    name: "Whistles - Robe satinée mi-longue à fente goutte d'eau - Jaune citron",
    price: {
      current: {
        value: 258.99,
        text: "258,99 €",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "EUR",
    },
    colour: "Lemon",
    colourWayId: 204878686,
    brandName: "Whistles",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 130650185,
    productType: "Product",
    url: "whistles/whistles-robe-satinee-mi-longue-a-fente-goutte-deau-jaune-citron/prd/204878684?clr=lemon&colourWayId=204878686",
    imageUrl:
      "images.asos-media.com/products/whistles-robe-satinee-mi-longue-a-fente-goutte-deau-jaune-citron/204878684-1-lemon",
    additionalImageUrls: [
      "images.asos-media.com/products/whistles-robe-satinee-mi-longue-a-fente-goutte-deau-jaune-citron/204878684-2",
      "images.asos-media.com/products/whistles-robe-satinee-mi-longue-a-fente-goutte-deau-jaune-citron/204878684-3",
      "images.asos-media.com/products/whistles-robe-satinee-mi-longue-a-fente-goutte-deau-jaune-citron/204878684-4",
    ],
    videoUrl:
      "video.asos-media.com/products/whistles-robe-satinee-mi-longue-a-fente-goutte-deau-jaune-citron/204878684-catwalk-AVS",
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 204972351,
    name: "Labelrail x Collyer Twins - Robe longue en dentelle à encolure carrée et manches bouffantes - Crème",
    price: {
      current: {
        value: 130.99,
        text: "130,99 €",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "EUR",
    },
    colour: "Crème",
    colourWayId: 204972356,
    brandName: "Labelrail",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 131384941,
    productType: "Product",
    url: "labelrail/labelrail-x-collyer-twins-robe-longue-en-dentelle-a-encolure-carree-et-manches-bouffantes-creme/prd/204972351?clr=creme&colourWayId=204972356",
    imageUrl:
      "images.asos-media.com/products/labelrail-x-collyer-twins-robe-longue-en-dentelle-a-encolure-carree-et-manches-bouffantes-creme/204972351-1-cream",
    additionalImageUrls: [
      "images.asos-media.com/products/labelrail-x-collyer-twins-robe-longue-en-dentelle-a-encolure-carree-et-manches-bouffantes-creme/204972351-2",
      "images.asos-media.com/products/labelrail-x-collyer-twins-robe-longue-en-dentelle-a-encolure-carree-et-manches-bouffantes-creme/204972351-3",
      "images.asos-media.com/products/labelrail-x-collyer-twins-robe-longue-en-dentelle-a-encolure-carree-et-manches-bouffantes-creme/204972351-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 204954566,
    name: "ASOS DESIGN Curve - Robe longe sans manches en mousseline - Violet",
    price: {
      current: {
        value: 125.99,
        text: "125,99 €",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "EUR",
    },
    colour: "Violet",
    colourWayId: 204954620,
    brandName: "ASOS EDITION",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 131279023,
    productType: "Product",
    url: "asos-edition/asos-design-curve-robe-longe-sans-manches-en-mousseline-violet/prd/204954566?clr=violet&colourWayId=204954620",
    imageUrl:
      "images.asos-media.com/products/asos-design-curve-robe-longe-sans-manches-en-mousseline-violet/204954566-1-purple",
    additionalImageUrls: [
      "images.asos-media.com/products/asos-design-curve-robe-longe-sans-manches-en-mousseline-violet/204954566-2",
      "images.asos-media.com/products/asos-design-curve-robe-longe-sans-manches-en-mousseline-violet/204954566-3",
      "images.asos-media.com/products/asos-design-curve-robe-longe-sans-manches-en-mousseline-violet/204954566-4",
    ],
    videoUrl:
      "video.asos-media.com/products/asos-design-curve-robe-longe-sans-manches-en-mousseline-violet/204954566-catwalk-AVS",
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 204972243,
    name: "Labelrail x Collyer Twins - Robe colonne en maille à rayures - Blanc et bleu marine",
    price: {
      current: {
        value: 108.99,
        text: "108,99 €",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "EUR",
    },
    colour: "Blanc/ bleu marine",
    colourWayId: 204972244,
    brandName: "Labelrail",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 131384945,
    productType: "Product",
    url: "labelrail/labelrail-x-collyer-twins-robe-colonne-en-maille-a-rayures-blanc-et-bleu-marine/prd/204972243?clr=blanc-bleu-marine&colourWayId=204972244",
    imageUrl:
      "images.asos-media.com/products/labelrail-x-collyer-twins-robe-colonne-en-maille-a-rayures-blanc-et-bleu-marine/204972243-1-whitenavy",
    additionalImageUrls: [
      "images.asos-media.com/products/labelrail-x-collyer-twins-robe-colonne-en-maille-a-rayures-blanc-et-bleu-marine/204972243-2",
      "images.asos-media.com/products/labelrail-x-collyer-twins-robe-colonne-en-maille-a-rayures-blanc-et-bleu-marine/204972243-3",
      "images.asos-media.com/products/labelrail-x-collyer-twins-robe-colonne-en-maille-a-rayures-blanc-et-bleu-marine/204972243-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 204107152,
    name: "Topshop - Robe mi-longue satinée en dentelle à fines bretelles - Ivoire et citron vert",
    price: {
      current: {
        value: 99.99,
        text: "99,99 €",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "EUR",
    },
    colour: "IVOIRE ET CITRON VERT",
    colourWayId: 204107153,
    brandName: "Topshop",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 125013448,
    productType: "Product",
    url: "topshop/topshop-robe-mi-longue-satinee-en-dentelle-a-fines-bretelles-ivoire-et-citron-vert/prd/204107152?clr=ivoire-et-citron-vert&colourWayId=204107153",
    imageUrl:
      "images.asos-media.com/products/topshop-robe-mi-longue-satinee-en-dentelle-a-fines-bretelles-ivoire-et-citron-vert/204107152-1-ivoryandlime",
    additionalImageUrls: [
      "images.asos-media.com/products/topshop-robe-mi-longue-satinee-en-dentelle-a-fines-bretelles-ivoire-et-citron-vert/204107152-2",
      "images.asos-media.com/products/topshop-robe-mi-longue-satinee-en-dentelle-a-fines-bretelles-ivoire-et-citron-vert/204107152-3",
      "images.asos-media.com/products/topshop-robe-mi-longue-satinee-en-dentelle-a-fines-bretelles-ivoire-et-citron-vert/204107152-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 204289377,
    name: "It's Now Cool - Robe courte de plage effet tie-dye de qualité supérieure - Multicolore",
    price: {
      current: {
        value: 94.99,
        text: "94,99 €",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "EUR",
    },
    colour: "Multicolore",
    colourWayId: 204289384,
    brandName: "It’s Now Cool",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: 135562,
    productCode: 126424111,
    productType: "MixMatchProduct",
    url: "its-now-cool/its-now-cool-haut-de-bikini-effet-tie-dye-rose/grp/135562?clr=multicolore&colourWayId=204289384#204289377",
    imageUrl:
      "images.asos-media.com/products/its-now-cool-robe-courte-de-plage-effet-tie-dye-de-qualite-superieure-multicolore/204289377-1-multi",
    additionalImageUrls: [
      "images.asos-media.com/products/its-now-cool-robe-courte-de-plage-effet-tie-dye-de-qualite-superieure-multicolore/204289377-2",
      "images.asos-media.com/products/its-now-cool-robe-courte-de-plage-effet-tie-dye-de-qualite-superieure-multicolore/204289377-3",
      "images.asos-media.com/products/its-now-cool-robe-courte-de-plage-effet-tie-dye-de-qualite-superieure-multicolore/204289377-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 204774350,
    name: "ASOS DESIGN Tall - Robe longue en satin mélangé à volants et dos nageur - Olive",
    price: {
      current: {
        value: 81.99,
        text: "81,99 €",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "EUR",
    },
    colour: "Vert olive",
    colourWayId: 204774352,
    brandName: "ASOS Tall",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 129251061,
    productType: "Product",
    url: "asos-tall/asos-design-tall-robe-longue-en-satin-melange-a-volants-et-dos-nageur-olive/prd/204774350?clr=vert-olive&colourWayId=204774352",
    imageUrl:
      "images.asos-media.com/products/asos-design-tall-robe-longue-en-satin-melange-a-volants-et-dos-nageur-olive/204774350-1-olivegreen",
    additionalImageUrls: [
      "images.asos-media.com/products/asos-design-tall-robe-longue-en-satin-melange-a-volants-et-dos-nageur-olive/204774350-2",
      "images.asos-media.com/products/asos-design-tall-robe-longue-en-satin-melange-a-volants-et-dos-nageur-olive/204774350-3",
      "images.asos-media.com/products/asos-design-tall-robe-longue-en-satin-melange-a-volants-et-dos-nageur-olive/204774350-4",
    ],
    videoUrl:
      "video.asos-media.com/products/asos-design-tall-robe-longue-en-satin-melange-a-volants-et-dos-nageur-olive/204774350-catwalk-AVS",
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 204774310,
    name: "ASOS DESIGN Petite - Robe longue en satin mélangé à volants et dos nageur - Rouille",
    price: {
      current: {
        value: 81.99,
        text: "81,99 €",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "EUR",
    },
    colour: "Rouille",
    colourWayId: 204774313,
    brandName: "ASOS Petite",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 129251062,
    productType: "Product",
    url: "asos-petite/asos-design-petite-robe-longue-en-satin-melange-a-volants-et-dos-nageur-rouille/prd/204774310?clr=rouille&colourWayId=204774313",
    imageUrl:
      "images.asos-media.com/products/asos-design-petite-robe-longue-en-satin-melange-a-volants-et-dos-nageur-rouille/204774310-1-rust",
    additionalImageUrls: [
      "images.asos-media.com/products/asos-design-petite-robe-longue-en-satin-melange-a-volants-et-dos-nageur-rouille/204774310-2",
      "images.asos-media.com/products/asos-design-petite-robe-longue-en-satin-melange-a-volants-et-dos-nageur-rouille/204774310-3",
      "images.asos-media.com/products/asos-design-petite-robe-longue-en-satin-melange-a-volants-et-dos-nageur-rouille/204774310-4",
    ],
    videoUrl:
      "video.asos-media.com/products/asos-design-petite-robe-longue-en-satin-melange-a-volants-et-dos-nageur-rouille/204774310-catwalk-AVS",
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 204943627,
    name: "Topshop - Robe nuisette - Jaune marbré",
    price: {
      current: {
        value: 72.99,
        text: "72,99 €",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "EUR",
    },
    colour: "JAUNE",
    colourWayId: 204943635,
    brandName: "Topshop",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 131154583,
    productType: "Product",
    url: "topshop/topshop-robe-nuisette-jaune-marbre/prd/204943627?clr=jaune&colourWayId=204943635",
    imageUrl:
      "images.asos-media.com/products/topshop-robe-nuisette-jaune-marbre/204943627-1-yellow",
    additionalImageUrls: [
      "images.asos-media.com/products/topshop-robe-nuisette-jaune-marbre/204943627-2",
      "images.asos-media.com/products/topshop-robe-nuisette-jaune-marbre/204943627-3",
      "images.asos-media.com/products/topshop-robe-nuisette-jaune-marbre/204943627-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 204050602,
    name: "Topshop - Robe portefeuille mi-longue élégante à imprimé fleuri - Violet",
    price: {
      current: {
        value: 72.99,
        text: "72,99 €",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "EUR",
    },
    colour: "VIOLET",
    colourWayId: 204050613,
    brandName: "Topshop",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 124368437,
    productType: "Product",
    url: "topshop/topshop-robe-portefeuille-mi-longue-elegante-a-imprime-fleuri-violet/prd/204050602?clr=violet&colourWayId=204050613",
    imageUrl:
      "images.asos-media.com/products/topshop-robe-portefeuille-mi-longue-elegante-a-imprime-fleuri-violet/204050602-1-purple",
    additionalImageUrls: [
      "images.asos-media.com/products/topshop-robe-portefeuille-mi-longue-elegante-a-imprime-fleuri-violet/204050602-2",
      "images.asos-media.com/products/topshop-robe-portefeuille-mi-longue-elegante-a-imprime-fleuri-violet/204050602-3",
      "images.asos-media.com/products/topshop-robe-portefeuille-mi-longue-elegante-a-imprime-fleuri-violet/204050602-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 205083713,
    name: "Nobody's Child - Alexa - Robe mi-longue à imprimé fleuri - Rose et rouge",
    price: {
      current: {
        value: 71.99,
        text: "71,99 €",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "EUR",
    },
    colour: "Rose/rouge",
    colourWayId: 205083714,
    brandName: "Nobody's Child",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 132185370,
    productType: "Product",
    url: "nobodys-child/nobodys-child-alexa-robe-mi-longue-a-imprime-fleuri-rose-et-rouge/prd/205083713?clr=rose-rouge&colourWayId=205083714",
    imageUrl:
      "images.asos-media.com/products/nobodys-child-alexa-robe-mi-longue-a-imprime-fleuri-rose-et-rouge/205083713-1-pinkred",
    additionalImageUrls: [
      "images.asos-media.com/products/nobodys-child-alexa-robe-mi-longue-a-imprime-fleuri-rose-et-rouge/205083713-2",
      "images.asos-media.com/products/nobodys-child-alexa-robe-mi-longue-a-imprime-fleuri-rose-et-rouge/205083713-3",
      "images.asos-media.com/products/nobodys-child-alexa-robe-mi-longue-a-imprime-fleuri-rose-et-rouge/205083713-4",
    ],
    videoUrl:
      "video.asos-media.com/products/nobodys-child-alexa-robe-mi-longue-a-imprime-fleuri-rose-et-rouge/205083713-catwalk-AVS",
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 204704711,
    name: "ASOS DESIGN - Robe longue en biais à imprimé floral avec mancherons et dos nu à lanières - Blanc",
    price: {
      current: {
        value: 69.99,
        text: "69,99 €",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "EUR",
    },
    colour: "Motif fleuri sur fond blanc",
    colourWayId: 204704712,
    brandName: "ASOS DESIGN",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 128947004,
    productType: "Product",
    url: "asos-design/asos-design-robe-longue-en-biais-a-imprime-floral-avec-mancherons-et-dos-nu-a-lanieres-blanc/prd/204704711?clr=motif-fleuri-sur-fond-blanc&colourWayId=204704712",
    imageUrl:
      "images.asos-media.com/products/asos-design-robe-longue-en-biais-a-imprime-floral-avec-mancherons-et-dos-nu-a-lanieres-blanc/204704711-1-whitebasedfloral",
    additionalImageUrls: [
      "images.asos-media.com/products/asos-design-robe-longue-en-biais-a-imprime-floral-avec-mancherons-et-dos-nu-a-lanieres-blanc/204704711-2",
      "images.asos-media.com/products/asos-design-robe-longue-en-biais-a-imprime-floral-avec-mancherons-et-dos-nu-a-lanieres-blanc/204704711-3",
      "images.asos-media.com/products/asos-design-robe-longue-en-biais-a-imprime-floral-avec-mancherons-et-dos-nu-a-lanieres-blanc/204704711-4",
    ],
    videoUrl:
      "video.asos-media.com/products/asos-design-robe-longue-en-biais-a-imprime-floral-avec-mancherons-et-dos-nu-a-lanieres-blanc/204704711-catwalk-AVS",
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 204097421,
    name: "ASOS DESIGN - Robe trapèze longue à encolure bandeau et dos élastique - Jaune vif",
    price: {
      current: {
        value: 68.99,
        text: "68,99 €",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "EUR",
    },
    colour: "Jaune vif",
    colourWayId: 204097422,
    brandName: "ASOS DESIGN",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 124828439,
    productType: "Product",
    url: "asos-design/asos-design-robe-trapeze-longue-a-encolure-bandeau-et-dos-elastique-jaune-vif/prd/204097421?clr=jaune-vif&colourWayId=204097422",
    imageUrl:
      "images.asos-media.com/products/asos-design-robe-trapeze-longue-a-encolure-bandeau-et-dos-elastique-jaune-vif/204097421-1-brightyellow",
    additionalImageUrls: [
      "images.asos-media.com/products/asos-design-robe-trapeze-longue-a-encolure-bandeau-et-dos-elastique-jaune-vif/204097421-2",
      "images.asos-media.com/products/asos-design-robe-trapeze-longue-a-encolure-bandeau-et-dos-elastique-jaune-vif/204097421-3",
      "images.asos-media.com/products/asos-design-robe-trapeze-longue-a-encolure-bandeau-et-dos-elastique-jaune-vif/204097421-4",
    ],
    videoUrl:
      "video.asos-media.com/products/asos-design-robe-trapeze-longue-a-encolure-bandeau-et-dos-elastique-jaune-vif/204097421-catwalk-AVS",
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 204219331,
    name: "Topshop - Robe mi-longue en maille au crochet avec bretelles en perles - Noir et blanc",
    price: {
      current: {
        value: 65.99,
        text: "65,99 €",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "EUR",
    },
    colour: "Mono",
    colourWayId: 204219341,
    brandName: "Topshop",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 125884442,
    productType: "Product",
    url: "topshop/topshop-robe-mi-longue-en-maille-au-crochet-avec-bretelles-en-perles-noir-et-blanc/prd/204219331?clr=mono&colourWayId=204219341",
    imageUrl:
      "images.asos-media.com/products/topshop-robe-mi-longue-en-maille-au-crochet-avec-bretelles-en-perles-noir-et-blanc/204219331-1-mono",
    additionalImageUrls: [
      "images.asos-media.com/products/topshop-robe-mi-longue-en-maille-au-crochet-avec-bretelles-en-perles-noir-et-blanc/204219331-2",
      "images.asos-media.com/products/topshop-robe-mi-longue-en-maille-au-crochet-avec-bretelles-en-perles-noir-et-blanc/204219331-3",
      "images.asos-media.com/products/topshop-robe-mi-longue-en-maille-au-crochet-avec-bretelles-en-perles-noir-et-blanc/204219331-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 204169901,
    name: "Topshop - Robe mi-longue en lin et broderie anglaise - Noir",
    price: {
      current: {
        value: 65.99,
        text: "65,99 €",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "EUR",
    },
    colour: "Noir",
    colourWayId: 204169902,
    brandName: "Topshop",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 125664088,
    productType: "Product",
    url: "topshop/topshop-robe-mi-longue-en-lin-et-broderie-anglaise-noir/prd/204169901?clr=noir&colourWayId=204169902",
    imageUrl:
      "images.asos-media.com/products/topshop-robe-mi-longue-en-lin-et-broderie-anglaise-noir/204169901-1-black",
    additionalImageUrls: [
      "images.asos-media.com/products/topshop-robe-mi-longue-en-lin-et-broderie-anglaise-noir/204169901-2",
      "images.asos-media.com/products/topshop-robe-mi-longue-en-lin-et-broderie-anglaise-noir/204169901-3",
      "images.asos-media.com/products/topshop-robe-mi-longue-en-lin-et-broderie-anglaise-noir/204169901-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 205215911,
    name: "ASOS DESIGN - Robe mi-longue dos nu à imprimé tacheté - Rouille",
    price: {
      current: {
        value: 60.99,
        text: "60,99 €",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "EUR",
    },
    colour: "ROUILLE À IMPRIMÉ TACHES",
    colourWayId: 205215921,
    brandName: "ASOS DESIGN",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 132454249,
    productType: "Product",
    url: "asos-design/asos-design-robe-mi-longue-dos-nu-a-imprime-tachete-rouille/prd/205215911?clr=rouille-a-imprime-taches&colourWayId=205215921",
    imageUrl:
      "images.asos-media.com/products/asos-design-robe-mi-longue-dos-nu-a-imprime-tachete-rouille/205215911-1-rustsmudge",
    additionalImageUrls: [
      "images.asos-media.com/products/asos-design-robe-mi-longue-dos-nu-a-imprime-tachete-rouille/205215911-2",
      "images.asos-media.com/products/asos-design-robe-mi-longue-dos-nu-a-imprime-tachete-rouille/205215911-3",
      "images.asos-media.com/products/asos-design-robe-mi-longue-dos-nu-a-imprime-tachete-rouille/205215911-4",
    ],
    videoUrl:
      "video.asos-media.com/products/asos-design-robe-mi-longue-dos-nu-a-imprime-tachete-rouille/205215911-catwalk-AVS",
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 204937795,
    name: "Style Cheat - Robe caraco courte en satin - Chartreuse",
    price: {
      current: {
        value: 60.99,
        text: "60,99 €",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "EUR",
    },
    colour: "Rouge/rose",
    colourWayId: 204937796,
    brandName: "Style Cheat",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 131120199,
    productType: "Product",
    url: "style-cheat/style-cheat-robe-caraco-courte-en-satin-chartreuse/prd/204937795?clr=rouge-rose&colourWayId=204937796",
    imageUrl:
      "images.asos-media.com/products/style-cheat-robe-caraco-courte-en-satin-chartreuse/204937795-1-redpink",
    additionalImageUrls: [
      "images.asos-media.com/products/style-cheat-robe-caraco-courte-en-satin-chartreuse/204937795-2",
      "images.asos-media.com/products/style-cheat-robe-caraco-courte-en-satin-chartreuse/204937795-3",
      "images.asos-media.com/products/style-cheat-robe-caraco-courte-en-satin-chartreuse/204937795-4",
    ],
    videoUrl:
      "video.asos-media.com/products/style-cheat-robe-caraco-courte-en-satin-chartreuse/204937795-catwalk-AVS",
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 205050400,
    name: "NA-KD - Robe courte avec encolure nouée - Crème",
    price: {
      current: {
        value: 58.99,
        text: "58,99 €",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "EUR",
    },
    colour: "Crème",
    colourWayId: 205050410,
    brandName: "NA-KD",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 131893803,
    productType: "Product",
    url: "na-kd/na-kd-robe-courte-avec-encolure-nouee-creme/prd/205050400?clr=creme&colourWayId=205050410",
    imageUrl:
      "images.asos-media.com/products/na-kd-robe-courte-avec-encolure-nouee-creme/205050400-1-cream",
    additionalImageUrls: [
      "images.asos-media.com/products/na-kd-robe-courte-avec-encolure-nouee-creme/205050400-2",
      "images.asos-media.com/products/na-kd-robe-courte-avec-encolure-nouee-creme/205050400-3",
      "images.asos-media.com/products/na-kd-robe-courte-avec-encolure-nouee-creme/205050400-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: true,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 205192737,
    name: "ASOS DESIGN - Robe plissée longue et asymétrique à manches volumineuses et imprimé animal - Orange",
    price: {
      current: {
        value: 50.99,
        text: "50,99 €",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "EUR",
    },
    colour: "Orange imprimé animal",
    colourWayId: 205192739,
    brandName: "ASOS DESIGN",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 132402874,
    productType: "Product",
    url: "asos-design/asos-design-robe-plissee-longue-et-asymetrique-a-manches-volumineuses-et-imprime-animal-orange/prd/205192737?clr=orange-imprime-animal&colourWayId=205192739",
    imageUrl:
      "images.asos-media.com/products/asos-design-robe-plissee-longue-et-asymetrique-a-manches-volumineuses-et-imprime-animal-orange/205192737-1-orangeanimal",
    additionalImageUrls: [
      "images.asos-media.com/products/asos-design-robe-plissee-longue-et-asymetrique-a-manches-volumineuses-et-imprime-animal-orange/205192737-2",
      "images.asos-media.com/products/asos-design-robe-plissee-longue-et-asymetrique-a-manches-volumineuses-et-imprime-animal-orange/205192737-3",
      "images.asos-media.com/products/asos-design-robe-plissee-longue-et-asymetrique-a-manches-volumineuses-et-imprime-animal-orange/205192737-4",
    ],
    videoUrl:
      "video.asos-media.com/products/asos-design-robe-plissee-longue-et-asymetrique-a-manches-volumineuses-et-imprime-animal-orange/205192737-catwalk-AVS",
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 204979224,
    name: "Kaiia - Robe courte en tulle transparent avec volants et mini rose en relief - Rose",
    price: {
      current: {
        value: 50.99,
        text: "50,99 €",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "EUR",
    },
    colour: "ROSE",
    colourWayId: 204979225,
    brandName: "Kaiia",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 131413767,
    productType: "Product",
    url: "kaiia/kaiia-robe-courte-en-tulle-transparent-avec-volants-et-mini-rose-en-relief-rose/prd/204979224?clr=rose&colourWayId=204979225",
    imageUrl:
      "images.asos-media.com/products/kaiia-robe-courte-en-tulle-transparent-avec-volants-et-mini-rose-en-relief-rose/204979224-1-pink",
    additionalImageUrls: [
      "images.asos-media.com/products/kaiia-robe-courte-en-tulle-transparent-avec-volants-et-mini-rose-en-relief-rose/204979224-2",
      "images.asos-media.com/products/kaiia-robe-courte-en-tulle-transparent-avec-volants-et-mini-rose-en-relief-rose/204979224-3",
      "images.asos-media.com/products/kaiia-robe-courte-en-tulle-transparent-avec-volants-et-mini-rose-en-relief-rose/204979224-4",
    ],
    videoUrl:
      "video.asos-media.com/products/kaiia-robe-courte-en-tulle-transparent-avec-volants-et-mini-rose-en-relief-rose/204979224-catwalk-AVS",
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 204843172,
    name: "ASOS DESIGN - Robe mi-longue fourreau moulante asymétrique avec boutons - Taupe",
    price: {
      current: {
        value: 50.99,
        text: "50,99 €",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "EUR",
    },
    colour: "TAUPE",
    colourWayId: 204843181,
    brandName: "ASOS DESIGN",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 130448712,
    productType: "Product",
    url: "asos-design/asos-design-robe-mi-longue-fourreau-moulante-asymetrique-avec-boutons-taupe/prd/204843172?clr=taupe&colourWayId=204843181",
    imageUrl:
      "images.asos-media.com/products/asos-design-robe-mi-longue-fourreau-moulante-asymetrique-avec-boutons-taupe/204843172-1-stone",
    additionalImageUrls: [
      "images.asos-media.com/products/asos-design-robe-mi-longue-fourreau-moulante-asymetrique-avec-boutons-taupe/204843172-2",
      "images.asos-media.com/products/asos-design-robe-mi-longue-fourreau-moulante-asymetrique-avec-boutons-taupe/204843172-3",
      "images.asos-media.com/products/asos-design-robe-mi-longue-fourreau-moulante-asymetrique-avec-boutons-taupe/204843172-4",
    ],
    videoUrl:
      "video.asos-media.com/products/asos-design-robe-mi-longue-fourreau-moulante-asymetrique-avec-boutons-taupe/204843172-catwalk-AVS",
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 205286311,
    name: "New Look - Robe portefeuille mi-longue à volants et imprimé animal - Marron",
    price: {
      current: {
        value: 47.99,
        text: "47,99 €",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "EUR",
    },
    colour: "Brown",
    colourWayId: 205286312,
    brandName: "New Look",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 132605353,
    productType: "Product",
    url: "new-look/new-look-robe-portefeuille-mi-longue-a-volants-et-imprime-animal-marron/prd/205286311?clr=brown&colourWayId=205286312",
    imageUrl:
      "images.asos-media.com/products/new-look-robe-portefeuille-mi-longue-a-volants-et-imprime-animal-marron/205286311-1-brown",
    additionalImageUrls: [
      "images.asos-media.com/products/new-look-robe-portefeuille-mi-longue-a-volants-et-imprime-animal-marron/205286311-2",
      "images.asos-media.com/products/new-look-robe-portefeuille-mi-longue-a-volants-et-imprime-animal-marron/205286311-3",
      "images.asos-media.com/products/new-look-robe-portefeuille-mi-longue-a-volants-et-imprime-animal-marron/205286311-4",
    ],
    videoUrl:
      "video.asos-media.com/products/new-look-robe-portefeuille-mi-longue-a-volants-et-imprime-animal-marron/205286311-catwalk-AVS",
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [
      {
        products: [
          {
            productId: 205263409,
          },
          {
            productId: 205263418,
          },
          {
            productId: 205286311,
          },
        ],
        type: "SupplierColour",
      },
    ],
    advertisement: null,
  },
  {
    id: 204843093,
    name: "ASOS DESIGN - Robe courte froncée en tulle avec haut caraco - Vert citron",
    price: {
      current: {
        value: 47.99,
        text: "47,99 €",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "EUR",
    },
    colour: "Vert citron",
    colourWayId: 204843114,
    brandName: "ASOS DESIGN",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 130448719,
    productType: "Product",
    url: "asos-design/asos-design-robe-courte-froncee-en-tulle-avec-haut-caraco-vert-citron/prd/204843093?clr=vert-citron&colourWayId=204843114",
    imageUrl:
      "images.asos-media.com/products/asos-design-robe-courte-froncee-en-tulle-avec-haut-caraco-vert-citron/204843093-1-limegreen",
    additionalImageUrls: [
      "images.asos-media.com/products/asos-design-robe-courte-froncee-en-tulle-avec-haut-caraco-vert-citron/204843093-2",
      "images.asos-media.com/products/asos-design-robe-courte-froncee-en-tulle-avec-haut-caraco-vert-citron/204843093-3",
      "images.asos-media.com/products/asos-design-robe-courte-froncee-en-tulle-avec-haut-caraco-vert-citron/204843093-4",
    ],
    videoUrl:
      "video.asos-media.com/products/asos-design-robe-courte-froncee-en-tulle-avec-haut-caraco-vert-citron/204843093-catwalk-AVS",
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 204777855,
    name: "ASOS DESIGN - Robe trapèze mi-longue en satin à corsage bandeau - Champagne",
    price: {
      current: {
        value: 47.99,
        text: "47,99 €",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "EUR",
    },
    colour: "Champagne",
    colourWayId: 204777856,
    brandName: "ASOS DESIGN",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 129251118,
    productType: "Product",
    url: "asos-design/asos-design-robe-trapeze-mi-longue-en-satin-a-corsage-bandeau-champagne/prd/204777855?clr=champagne&colourWayId=204777856",
    imageUrl:
      "images.asos-media.com/products/asos-design-robe-trapeze-mi-longue-en-satin-a-corsage-bandeau-champagne/204777855-1-champagne",
    additionalImageUrls: [
      "images.asos-media.com/products/asos-design-robe-trapeze-mi-longue-en-satin-a-corsage-bandeau-champagne/204777855-2",
      "images.asos-media.com/products/asos-design-robe-trapeze-mi-longue-en-satin-a-corsage-bandeau-champagne/204777855-3",
      "images.asos-media.com/products/asos-design-robe-trapeze-mi-longue-en-satin-a-corsage-bandeau-champagne/204777855-4",
    ],
    videoUrl:
      "video.asos-media.com/products/asos-design-robe-trapeze-mi-longue-en-satin-a-corsage-bandeau-champagne/204777855-catwalk-AVS",
    showVideo: false,
    isSellingFast: true,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 205159978,
    name: "Noisy May - Robe longue en tulle à imprimé coucher de soleil - Multicolore",
    price: {
      current: {
        value: 44.99,
        text: "44,99 €",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "EUR",
    },
    colour: "Multicolore",
    colourWayId: 205159979,
    brandName: "Noisy May",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 132339732,
    productType: "Product",
    url: "noisy-may/noisy-may-robe-longue-en-tulle-a-imprime-coucher-de-soleil-multicolore/prd/205159978?clr=multicolore&colourWayId=205159979",
    imageUrl:
      "images.asos-media.com/products/noisy-may-robe-longue-en-tulle-a-imprime-coucher-de-soleil-multicolore/205159978-1-multi",
    additionalImageUrls: [
      "images.asos-media.com/products/noisy-may-robe-longue-en-tulle-a-imprime-coucher-de-soleil-multicolore/205159978-2",
      "images.asos-media.com/products/noisy-may-robe-longue-en-tulle-a-imprime-coucher-de-soleil-multicolore/205159978-3",
      "images.asos-media.com/products/noisy-may-robe-longue-en-tulle-a-imprime-coucher-de-soleil-multicolore/205159978-4",
    ],
    videoUrl:
      "video.asos-media.com/products/noisy-may-robe-longue-en-tulle-a-imprime-coucher-de-soleil-multicolore/205159978-catwalk-AVS",
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 205188591,
    name: "ASOS DESIGN - Robe portefeuille mi-longue plissée à petites fleurs et liens sur le côté",
    price: {
      current: {
        value: 43.99,
        text: "43,99 €",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "EUR",
    },
    colour: "Imprimé fleuri",
    colourWayId: 205188640,
    brandName: "ASOS DESIGN",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 132384998,
    productType: "Product",
    url: "asos-design/asos-design-robe-portefeuille-mi-longue-plissee-a-petites-fleurs-et-liens-sur-le-cote/prd/205188591?clr=imprime-fleuri&colourWayId=205188640",
    imageUrl:
      "images.asos-media.com/products/asos-design-robe-portefeuille-mi-longue-plissee-a-petites-fleurs-et-liens-sur-le-cote/205188591-1-floral",
    additionalImageUrls: [
      "images.asos-media.com/products/asos-design-robe-portefeuille-mi-longue-plissee-a-petites-fleurs-et-liens-sur-le-cote/205188591-2",
      "images.asos-media.com/products/asos-design-robe-portefeuille-mi-longue-plissee-a-petites-fleurs-et-liens-sur-le-cote/205188591-3",
      "images.asos-media.com/products/asos-design-robe-portefeuille-mi-longue-plissee-a-petites-fleurs-et-liens-sur-le-cote/205188591-4",
    ],
    videoUrl:
      "video.asos-media.com/products/asos-design-robe-portefeuille-mi-longue-plissee-a-petites-fleurs-et-liens-sur-le-cote/205188591-catwalk-AVS",
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 204727091,
    name: "Daisy Street - Robe nuisette mi-longue satinée à col bénitier - Vert",
    price: {
      current: {
        value: 40.99,
        text: "40,99 €",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "EUR",
    },
    colour: "Marbré vert",
    colourWayId: 204727095,
    brandName: "Daisy Street",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 129029213,
    productType: "Product",
    url: "daisy-street/daisy-street-robe-nuisette-mi-longue-satinee-a-col-benitier-vert/prd/204727091?clr=marbre-vert&colourWayId=204727095",
    imageUrl:
      "images.asos-media.com/products/daisy-street-robe-nuisette-mi-longue-satinee-a-col-benitier-vert/204727091-1-greenmarble",
    additionalImageUrls: [
      "images.asos-media.com/products/daisy-street-robe-nuisette-mi-longue-satinee-a-col-benitier-vert/204727091-2",
      "images.asos-media.com/products/daisy-street-robe-nuisette-mi-longue-satinee-a-col-benitier-vert/204727091-3",
      "images.asos-media.com/products/daisy-street-robe-nuisette-mi-longue-satinee-a-col-benitier-vert/204727091-4",
    ],
    videoUrl:
      "video.asos-media.com/products/daisy-street-robe-nuisette-mi-longue-satinee-a-col-benitier-vert/204727091-catwalk-AVS",
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 204779177,
    name: "The North Face - Robe t-shirt - Violet - Exclusivité ASOS",
    price: {
      current: {
        value: 40,
        text: "40,00 €",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "EUR",
    },
    colour: "Violet",
    colourWayId: 204779180,
    brandName: "The North Face",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 129268652,
    productType: "Product",
    url: "the-north-face/the-north-face-robe-t-shirt-violet-exclusivite-asos/prd/204779177?clr=violet&colourWayId=204779180",
    imageUrl:
      "images.asos-media.com/products/the-north-face-robe-t-shirt-violet-exclusivite-asos/204779177-1-purple",
    additionalImageUrls: [
      "images.asos-media.com/products/the-north-face-robe-t-shirt-violet-exclusivite-asos/204779177-2",
      "images.asos-media.com/products/the-north-face-robe-t-shirt-violet-exclusivite-asos/204779177-3",
      "images.asos-media.com/products/the-north-face-robe-t-shirt-violet-exclusivite-asos/204779177-4",
    ],
    videoUrl:
      "video.asos-media.com/products/the-north-face-robe-t-shirt-violet-exclusivite-asos/204779177-catwalk-AVS",
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [
      {
        products: [
          {
            productId: 204779154,
          },
          {
            productId: 204779283,
          },
          {
            productId: 204779177,
          },
        ],
        type: "SupplierColour",
      },
    ],
    advertisement: null,
  },
  {
    id: 204769399,
    name: "Vila - Robe caraco mi-longue en satin nouée dans le dos - Neutre à zébrures",
    price: {
      current: {
        value: 39.99,
        text: "39,99 €",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "EUR",
    },
    colour: "Imprimé zèbre",
    colourWayId: 204769418,
    brandName: "Vila",
    hasVariantColours: false,
    hasMultiplePrices: true,
    groupId: null,
    productCode: 129219107,
    productType: "Product",
    url: "vila/vila-robe-caraco-mi-longue-en-satin-nouee-dans-le-dos-neutre-a-zebrures/prd/204769399?clr=imprime-zebre&colourWayId=204769418",
    imageUrl:
      "images.asos-media.com/products/vila-robe-caraco-mi-longue-en-satin-nouee-dans-le-dos-neutre-a-zebrures/204769399-1-zebraprint",
    additionalImageUrls: [
      "images.asos-media.com/products/vila-robe-caraco-mi-longue-en-satin-nouee-dans-le-dos-neutre-a-zebrures/204769399-2",
      "images.asos-media.com/products/vila-robe-caraco-mi-longue-en-satin-nouee-dans-le-dos-neutre-a-zebrures/204769399-3",
      "images.asos-media.com/products/vila-robe-caraco-mi-longue-en-satin-nouee-dans-le-dos-neutre-a-zebrures/204769399-4",
    ],
    videoUrl:
      "video.asos-media.com/products/vila-robe-caraco-mi-longue-en-satin-nouee-dans-le-dos-neutre-a-zebrures/204769399-catwalk-AVS",
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 204874387,
    name: "ASOS DESIGN - Robe nuisette courte en satin à encolure nageur - Vert vif",
    price: {
      current: {
        value: 33,
        text: "33,00 €",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "EUR",
    },
    colour: "Vert",
    colourWayId: 204874388,
    brandName: "ASOS DESIGN",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 130613229,
    productType: "Product",
    url: "asos-design/asos-design-robe-nuisette-courte-en-satin-a-encolure-nageur-vert-vif/prd/204874387?clr=vert&colourWayId=204874388",
    imageUrl:
      "images.asos-media.com/products/asos-design-robe-nuisette-courte-en-satin-a-encolure-nageur-vert-vif/204874387-1-green",
    additionalImageUrls: [
      "images.asos-media.com/products/asos-design-robe-nuisette-courte-en-satin-a-encolure-nageur-vert-vif/204874387-2",
      "images.asos-media.com/products/asos-design-robe-nuisette-courte-en-satin-a-encolure-nageur-vert-vif/204874387-3",
      "images.asos-media.com/products/asos-design-robe-nuisette-courte-en-satin-a-encolure-nageur-vert-vif/204874387-4",
    ],
    videoUrl:
      "video.asos-media.com/products/asos-design-robe-nuisette-courte-en-satin-a-encolure-nageur-vert-vif/204874387-catwalk-AVS",
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
];

module.exports = summerWoman;
